# Values formatted like "_env:ENV_VAR_NAME:default_value" can be overridden by the specified environment variable.
# See https://github.com/yesodweb/yesod/wiki/Configuration#overriding-configuration-values-with-environment-variables

static-dir:     "_env:STATIC_DIR:static"
host:           "_env:HOST:*4" # any IPv4 host
port:           "_env:PORT:3000"
approot:        "_env:APPROOT:http://localhost:3000"
ip-from-header: "_env:IP_FROM_HEADER:false"

# Optional values with the following production defaults.
# In development, they default to the inverse.
#
# development: false
# detailed-logging: false
# should-log-all: false
# reload-templates: false
# mutable-static: false
# skip-combining: false

database:
  database: "_env:SQLITE_DATABASE:blog.sqlite3"
  poolsize: "_env:SQLITE_POOLSIZE:10"

copyright: Insert copyright statement here
#analytics: UA-YOURCODE

# Limits:
max_nr_comments: 100
max_comment_length: 100000

# For the RSS feed:
rss_web_master: "Carlo Hamalainen"
rss_language: "en-US"
rss_copyright: "Carlo Hamalainen"

email_notification_from_name:     "blog"
email_notification_from_address:  "carlo@carlo-hamalainen.net"

email_notification_to_name:     "blog"
email_notification_to_address:  "carlo@carlo-hamalainen.net"

base_url: "blog"
